// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLUBspI1qp8YyRCWVi8ggmS2GkLvCPDBU',
    appId: '1:865467467489:web:16c5acc3b380f621c559a0',
    messagingSenderId: '865467467489',
    projectId: 'to-do-list-63627',
    authDomain: 'to-do-list-63627.firebaseapp.com',
    storageBucket: 'to-do-list-63627.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJiy47mraeJmYs99wd1_vz6VFEE3c7psU',
    appId: '1:865467467489:android:26667fcbb6cf2fdcc559a0',
    messagingSenderId: '865467467489',
    projectId: 'to-do-list-63627',
    storageBucket: 'to-do-list-63627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeL09YDnpGpkmTelwl_8Cai7-eXZfSdoU',
    appId: '1:865467467489:ios:0a945b603157b661c559a0',
    messagingSenderId: '865467467489',
    projectId: 'to-do-list-63627',
    storageBucket: 'to-do-list-63627.appspot.com',
    iosClientId: '865467467489-d6c5och61b3vn3jahln2vpf3e12tkpeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.soda4thHapit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeL09YDnpGpkmTelwl_8Cai7-eXZfSdoU',
    appId: '1:865467467489:ios:f6ea49ef8bc4cb05c559a0',
    messagingSenderId: '865467467489',
    projectId: 'to-do-list-63627',
    storageBucket: 'to-do-list-63627.appspot.com',
    iosClientId: '865467467489-7ja7lmostv6jei6r589rndlnbrr1vlg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.soda4thHapit.RunnerTests',
  );
}
